#!/usr/bin/perl
use strict;
# clipbored - daemon that saves all X selections for use with dmenuclip
# Copyright (C) 2010 Magnus Woldrich <trapd00r@trapd00r.se>
use App::Daemon qw(daemonize);
use Getopt::Long;
#use Data::Dumper;

my $xsel = "$ENV{'HOME'}/.config/clipbored/clips";

GetOptions('h|help' =>  \&usage);

sub syncIt {
  print "Daemonizing...\n";
  daemonize();
  while(1) {
    open(XSEL,"<", $xsel) or die "Cant open $xsel for reading: $!";
    my @lines = <XSEL>;
    chomp @lines;
    close XSEL;
    my $currentSel = `/usr/bin/xsel -o`;
    chomp($currentSel);
    $currentSel =~ s/\n/ /g; #temporary (?) fix for the newline hassle
    #print Dumper($currentSel);
    if($currentSel ~~ @lines) {
      &syncSec(0);
    }
    else {
      open(XSEL_W, ">>", $xsel) or die "Cant open $xsel for writing: $!";
      print XSEL_W "$currentSel\n";
      close XSEL_W;
    }
    sleep 2;
  }
}

&syncIt;

sub usage {
  print << "USAGE";
  $0 (start|stop|status)
  $0 [OPTIONS]
  OPTIONS
    -X  run in foreground
    -l  log to file
    -u  user to run as
    -p  pid file location

USAGE
exit 0;
}

# Those are deprecated, but left here for reference (and the dummy call)
sub syncPrim {
  system("/usr/bin/xclip -o --selection primary -o) >> $xsel&&printf \"\n\" >> $xsel");
}
sub syncSec {
  my $c = shift;
  unless($c == 0) {
    system("/usr/bin/xclip -o >> $xsel"); #&& printf \"\n\" >> $xsel");
  }
}
