

=pod

=head1 NAME

  clipbored - continuously collects all selections in Xorg's clipboard buffers

=head1 SYNOPSIS

  clipbored [OPTIONS]

=head1 DESCRIPTION

B<clipbored> is a daemon that continuously grabs all non-duplicate selections
in the X.org clipboard buffers and writes them to a plaintext history file for
later use.

There are several scripts distributed with clipbored that'll use the history
file for different purposes.

=head2 Scripts

  dmenurl   - launch dmenu with all previously yanked URLs for you to select
              from.

  dmenuclip - launch dmenu listing all previously clipboarded content

  fmenuclip - do the same thing but vertically

=head1 OPTIONS

  -n,   --no-daemon   do not detach from the shell
  -k,   --kill        kill a running clipbored session
  -h,   --help        show this help
  -m,   --man         display the manual

=head1 ENVIRONMENT

The history file will be placed in $XDG_DATA_HOME/clipbored/clips

=head1 AUTHOR

Written by Magnus Woldrich.

=head1 REPORTING BUGS

Report bugs to trapd00r@trapd00r.se

clipbored home page: <http://github.com/trapd00r/clipbored/>

=head1 COPYRIGHT

(C) Copyright 2010 Magnus Woldrich.

License GPLv2: GNU GPL version 2

=cut
