#!/usr/bin/perl
use strict;
# dmenurl - pick and choose url's in the xsel file

my $xsels = "$ENV{XDG_DATA_HOME}/clipbored/clips";
my $dmenu = 'dmenu -b -l 10';

open(my $r_clips, '<', $xsels) or die("Cant open $xsels: $!");
my @cliplist = <$r_clips>;
close($r_clips);

my @urls;
for my $clip(@cliplist) {
  if($clip =~ m;(https?://([-\w\.]+)+(:\d+)?(/([\w/_\.]*(\?\S+)?)?)?);) {
    push(@urls, $1);
  }
}
my $urls_to_print = join('\n', reverse(@urls));

chomp(my $xclip = `which xclip`);

do {
  print STDERR "No xclip found. Please install.\n";
  exit(1);
} if(!defined($xclip));

$xclip = "$xclip -i -l 0|$xclip -o";

system("printf \"$urls_to_print\"|$dmenu -p url|$xclip");
