#!/usr/bin/perl
# fmenuclip - Really nasty dmenu launcher to be used in combination with
# clipbored
# Authors notice; Since this is what I use, it is what will be maintained
use strict;

my $xsels = "$ENV{XDG_DATA_HOME}/clipbored/clips";
my $f     = '-*-fixed-*-*-*-*-15-*-*-*-*-*-*-*';
#my $dmenu = 'fmenu -i -b -nb -l 7 \#1c1c1c -nf \#d7005f -sb \#252525';
my $dmenu = 'dmenu -b -l 10'; #dmenu with vertical patch, or fmenu

my $xclipper = `which xclip` || `which xsel` || undef;
chomp($xclipper);
die("No xsel or xclip in $ENV{PATH}") if(!defined($xclipper));

if($xclipper =~ /xclip/) {
  $xclipper = "$xclipper -i -l 0|$xclipper -o";
}
else {
    $xclipper = "$xclipper -i|$xclipper -o";
}
# this rocks! :)
system("printf \"\$(\\tac $xsels|$dmenu -fn $f -p xsel)\"|$xclipper");
