#!/usr/bin/perl
# fmenuclip - Really nasty dmenu launcher to be used in combination with
# clipbored
# Authors notice; Since this is what I use, it is what will be maintained
use strict;

my $xsels     = "$ENV{XDG_DATA_HOME}/clipbored/clips";

my $font      = (exists $ENV{CLIPBORED_DMENU_FONT})
  ? $ENV{CLIPBORED_DMENU_FONT}
  : '-*-fixed-*-*-*-*-15-*-*-*-*-*-*-*';
my $normal_bg = (exists $ENV{CLIPBORED_DMENU_NORMAL_BG})
  ? $ENV{CLIPBORED_DMENU_NORMAL_BG}
  :  "#1c1c1c";
my $normal_fg = (exists $ENV{CLIPBORED_DMENU_NORMAL_FG})
  ? $ENV{CLIPBORED_DMENU_NORMAL_FG}
  : "#ffffff";
my $select_bg = (exists $ENV{CLIPBORED_DMENU_SELECT_BG})
  ? $ENV{CLIPBORED_DMENU_SELECT_BG}
  : "#484848";
my $select_fg = (exists $ENV{CLIPBORED_DMENU_SELECT_FG})
  ? $ENV{CLIPBORED_DMENU_SELECT_FG}
  :  "#ffffff";

$normal_bg =~ s/^(#)/\\$1/;
$normal_fg =~ s/^(#)/\\$1/;
$select_bg =~ s/^(#)/\\$1/;
$select_fg =~ s/^(#)/\\$1/;

my $dmenu =  "fmenu -i -b -l 10 -fn $font "
  . "-nb $normal_bg -nf $normal_fg -sb $select_bg -sf $select_fg";

chomp(my $xclipper = `which xclip`);

die("No  xclip in $ENV{PATH}") if(!defined($xclipper));

$xclipper .= " -i -l 0|$xclipper -o";

system("printf \"\$(\\tac $xsels|$dmenu  -p xsel)\"|$xclipper");
